eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  server:
    port: 5${server.port}
    servlet:
      context-path: /management
  endpoints:
    web:
      exposure:
        include: '*'
