server:
  port: ${EUREKA_PORT:8761}

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${server.port}/eureka/
